# @package _global_
learner:
  hparams:
    model:
      regularization_loss_heads:
        rotation_prediction:
          head:
            _target_: sesemi.models.heads.loss.RotationPredictionLossHead
            data: rotation_prediction
            backbone: supervised_backbone
