# @package _global_
learner:
  hparams:
    model:
      regularization_loss_heads:
        jigsaw_prediction:
          head:
            _target_: sesemi.models.loss_heads.JigsawPredictionLossHead
            data: unsupervised
            backbone: supervised_backbone