# @package _global_
learner:
  hparams:
    model:
      regularization_loss_heads:
        jigsaw_prediction:
          head:
            _target_: sesemi.models.heads.loss.JigsawPredictionLossHead
            input_data: unsupervised
            input_backbone: backbone