#
# Copyright 2021, Flyreel. All Rights Reserved.
# =============================================#
"""Interface definition for backbones."""
import torch.nn as nn


class Backbone(nn.Module):
    """The interface for image classification backbones.

    Attributes:
        out_features: The number of output features generated by the backbone.
    """

    out_features: int
