# @package _global_
learner:
  hparams:
    model:
      regularization_loss_heads:
        rotation_prediction:
          head:
            _target_: sesemi.models.heads.loss.RotationPredictionLossHead
            data: unsupervised
            backbone: supervised_backbone
          scheduler:
            _target_: sesemi.schedulers.weight.SigmoidRampupScheduler
            weight: 1.0
            stop_rampup: 0
          scale_factor: 1.0
        entropy_minimization:
          head:
            _target_: sesemi.models.heads.loss.EntropyMinimizationLossHead
            data: unsupervised
            backbone: supervised_backbone
            head: supervised_head
          scheduler:
            _target_: sesemi.schedulers.weight.SigmoidRampupScheduler
            weight: 1.0
            stop_rampup: 0
          scale_factor: 1.0