# @package _global_
defaults:
  - /base/sesemi
  - /learner: classifier
  - _self_
hydra:
  sweep:
    dir: ${run.dir}/${run.id}/${now:%Y%m%d_%H%M%S}
    subdir: ${hydra.job.num}
  run:
    dir: ${run.dir}/${run.id}/${now:%Y%m%d_%H%M%S}
