# @package _global_
learner:
  hparams:
    model:
      backbone:
        _target_: sesemi.PyTorchImageModel
        freeze: False
        pretrained: False
        global_pool: avg
        drop_rate: 0.5