# @package _global_
learner:
  hparams:
    model:
      regularization_loss_heads:
        entropy_minimization:
          head:
            _target_: sesemi.models.loss_heads.EntropyMinimizationLossHead
            data: unsupervised
            backbone: supervised_backbone
