# @package _global_
learner:
  hparams:
    model:
      regularization_loss_heads:
        entropy_minimization:
          head:
            _target_: sesemi.models.heads.loss.EntropyMinimizationLossHead
            input_data: unsupervised
            input_backbone: backbone