defaults:
  - /ops/pseudo_dataset
preprocessing_transform:
  _target_: sesemi.transforms.center_crop_transforms
  resize: 256
  crop_dim: 224
dataset:
  name: image_folder
  subset: [val, unsup]
output_dir: ./data/pseudo_stage_1
