# @package _global_
learner:
  hparams:
    model:
      ema:
        decay: 0.999
      regularization_loss_heads:
        fixmatch:
          head:
            _target_: sesemi.models.loss_heads.FixMatchLossHead
            data: fixmatch
            student_backbone: supervised_backbone
            student_head: supervised_head
            teacher_backbone: supervised_backbone_ema
            teacher_head: supervised_head_ema